[workspace]
resolver = "2"
members = [
    "approximate_count_distinct",
    "avl_tree",
    "binary-search-collection",
    "build-rs-inputs",
    "build-script-env-vars",
    "clone_on_mut",
    "closures",
    "cpf-cnpj",
    "cpf-cnpj-cli",
    "deterministic-chooser",
    "dices_probabilities",
    "emulated_closures",
    "enum-indexed",
    "enum-indexed/macro",
    "enum-indexed/renamed-crate-test",
    "floating-point-explorer",
    "fn-bind",
    "happy_number",
    "hlist",
    "insertion_order_hash_map",
    "interlace",
    "iters",
    "json-diff",
    "method-resolution",
    "min-max-binary-heap", 
    "music",
    "ratatui-scrolling",
    "ref_count",
    "rewrap-rustdoc",
    "same-elements",
    "shared_ownership",
    "syn-dump",
    "tailcall",
    "version-sorting",
    "wavelength-to-rgb",
]

[workspace.lints.clippy]
pedantic = "warn"
