[workspace]
resolver = "2"
members = [
    "approximate-count-distinct",
    "avl-tree",
    "binary-search-collection",
    "build-rs-inputs",
    "build-script-env-vars",
    "clone-on-mut",
    "closures",
    "cpf-cnpj",
    "cpf-cnpj-cli",
    "deterministic-chooser",
    "dices-probabilities",
    "emulated-closures",
    "enum-indexed",
    "enum-indexed/macro",
    "enum-indexed/renamed-crate-test",
    "floating-point-explorer",
    "fn-bind",
    "happy-number",
    "hlist",
    "indexed",
    "insertion-order-hash-map",
    "interlace",
    "iters",
    "json-diff",
    "method-resolution",
    "min-max-binary-heap",
    "music",
    "ratatui-scrolling",
    "ref-count",
    "rewrap-rustdoc",
    "same-elements",
    "shared-ownership",
    "summations",
    "syn-dump",
    "tailcall",
    "version-sorting",
    "wavelength-to-rgb",
]

[workspace.dependencies]
cpf-cnpj.path = "cpf-cnpj"
enum-indexed.path = "enum-indexed"
indexed = { path = "indexed", default-features = false }
syn-dump.path = "syn-dump"

[workspace.lints.clippy]
pedantic = "warn"
