set allow-duplicate-recipes

import '../justfile'

default: fmt test clippy

[no-cd]
check *ARGS:
  cargo check \
    -p enum-indexed \
    -p enum-indexed-macro \
    -p enum-indexed-renamed-crate-test \
    {{ARGS}}

[no-cd]
fmt:
  cargo +nightly fmt \
    -p enum-indexed \
    -p enum-indexed-macro \
    -p enum-indexed-renamed-crate-test \
    -- \
    --config group_imports=StdExternalCrate \
    --config imports_granularity=Module \
    --config wrap_comments=true \
    --config comment_width=100 \
    --config format_code_in_doc_comments=true

[no-cd]
test *ARGS:
  cargo test \
    -p enum-indexed \
    -p enum-indexed-macro \
    -p enum-indexed-renamed-crate-test \
    {{ARGS}}

[no-cd]
clippy:
  cargo clippy --all-targets \
    -p enum-indexed \
    -p enum-indexed-macro \
    -p enum-indexed-renamed-crate-test
