[package]
name = "binary-search-collection"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
default = ["std"]
std = []
alternative-line-binary_search = []
alternative-line_buffered-binary_search-1 = []
alternative-line_buffered-binary_search-2 = []
alternative-subslice-binary_search = []

[lints]
workspace = true
