set allow-duplicate-recipes

import '../justfile'

default: check fmt test-variants clippy

check:
  cargo check --no-default-features
  cargo check --no-default-features --features std

test-variants *ARGS: test
  cargo test {{ARGS}}
  cargo test --features '\
    alternative-line-binary_search \
    alternative-line_buffered-binary_search-1 \
    alternative-subslice-binary_search \
    ' \
    {{ARGS}}
  cargo test --features '\
    alternative-line_buffered-binary_search-2 \
    ' \
    {{ARGS}}

clippy:
  cargo clippy --all-targets --no-default-features
  cargo clippy --all-targets --no-default-features --features std

doc *ARGS:
  cargo +nightly doc {{ARGS}}
